// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/home/:id": {
    params: {
      "id": string;
    };
  };
  "/home/new": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signup" | "/home" | "/home/:id" | "/home/new";
  };
  "./Authentication/Login/login.tsx": {
    id: "Authentication/Login/login";
    page: "/";
  };
  "./Authentication/Signup/signup.tsx": {
    id: "Authentication/Signup/signup";
    page: "/signup";
  };
  "./Layout/ProtectedRoute.tsx": {
    id: "Layout/ProtectedRoute";
    page: "/" | "/home" | "/home/:id" | "/home/new";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
  "./components/HistoryChat/HistoryChat.tsx": {
    id: "components/HistoryChat/HistoryChat";
    page: "/home/:id";
  };
  "./components/Newchat/Newchat.tsx": {
    id: "components/Newchat/Newchat";
    page: "/home/new";
  };
};