// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/home": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signup" | "/home";
  };
  "./Authentication/Login/login.tsx": {
    id: "Authentication/Login/login";
    page: "/";
  };
  "./Authentication/Signup/signup.tsx": {
    id: "Authentication/Signup/signup";
    page: "/signup";
  };
  "./Layout/ProtectedRoute.tsx": {
    id: "Layout/ProtectedRoute";
    page: "/" | "/home";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
};